spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fintech?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    defer-datasource-initialization: true

  jwt:
    header : Authorization
    prefix : Bearer
    secret : fintechService0123456789
    token-valid-time : 3600000 # 1hour