### 회원가입 (고객)
POST http://localhost:8080/api/user/signUp
Content-Type: application/json

{
  "userName": "masjdhask",
  "phone": "010-4592-1718",
  "password": "asdsadsa"
}

### 로그인 (고객)
POST http://localhost:8080/api/user/signIn
Content-Type: application/json

{
  "phone": "010-4592-1718",
  "password": "asdsadsa"
}

### 계좌 생성
POST http://localhost:8080/api/account/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAtNDU5Mi0xNzE4IiwianRpIjoiK1NPajh5WW4yR1FHS2RNVUFLcjFQSGRLV1duNHhZb0hLZnNMZFNMOWJ0dz0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNzA5MzU3MDYxLCJleHAiOjE3MDkzNjA2NjF9.wp6hnHuMoLG5aOBvAfKnspGergsytzfiSxM_gDbRF9E

{
  "userId": 1,
  "initialBalance": 0,
  "accountName": "1232345"
}

### 계좌 조회
GET http://localhost:8080/api/account/info?userId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAtNDU5Mi0xNzE4IiwianRpIjoiK1NPajh5WW4yR1FHS2RNVUFLcjFQSGRLV1duNHhZb0hLZnNMZFNMOWJ0dz0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNzA5MzU3MDYxLCJleHAiOjE3MDkzNjA2NjF9.wp6hnHuMoLG5aOBvAfKnspGergsytzfiSxM_gDbRF9E

### 계좌 해지
DELETE http://localhost:8080/api/account/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAtNDU5Mi0xNzE4IiwianRpIjoiK1NPajh5WW4yR1FHS2RNVUFLcjFQSGRLV1duNHhZb0hLZnNMZFNMOWJ0dz0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNzA5MzU3MDYxLCJleHAiOjE3MDkzNjA2NjF9.wp6hnHuMoLG5aOBvAfKnspGergsytzfiSxM_gDbRF9E

{
  "userId": 1,
  "accountNumber": "33300000002"
}