### 회원가입 (고객)
POST http://localhost:8080/api/user/signUp
Content-Type: application/json

{
  "userName": "masjdhask",
  "phone": "010-4592-1718",
  "password": "asdsadsa"
}

### 로그인 (고객)
POST http://localhost:8080/api/user/signIn
Content-Type: application/json

{
  "phone": "010-4592-1718",
  "password": "asdsadsa"
}

### 계좌 생성
POST http://localhost:8080/api/account/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAtNDU5Mi0xNzE4IiwianRpIjoidDZqcmw1MWVzc2gvMkUrRlJMdEhsK3ZyaThHQ2FzaFZwQ2toRFRkY1ErQT0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNzA5Mjg4MzA0LCJleHAiOjE3MDkyOTE5MDR9.NaonDUi6MUdoRl3H57cVgEtjCekt5Eq53ZhsmBeFRoE

{
  "userId": 1,
  "initialBalance": 1000,
  "accountName": "1232345"
}

### 계좌 조회
GET http://localhost:8080/api/account/info?userId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAtNDU5Mi0xNzE4IiwianRpIjoiSXdOTjJ1MG83dzAwbHZiazBIWElYZnZ4K2lCWXRCMERXb3ZZdnZ0RHFlbz0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNzA5Mjg1OTUxLCJleHAiOjE3MDkyODk1NTF9.dazXLv2XKjRZGlN_7YB0JyoebiKfxf3tAeTuPRHThI0

### 계좌 해지
DELETE http://localhost:8080/api/account/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAtNDU5Mi0xNzE4IiwianRpIjoiSXdOTjJ1MG83dzAwbHZiazBIWElYZnZ4K2lCWXRCMERXb3ZZdnZ0RHFlbz0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNzA5Mjg1OTUxLCJleHAiOjE3MDkyODk1NTF9.dazXLv2XKjRZGlN_7YB0JyoebiKfxf3tAeTuPRHThI0

{
  "userId": 1,
  "accountNumber": "33300000001"
}